utils::globalVariables(c('ADJ_FACTOR_MACR', 'ADJ_FACTOR_MICR', 'ADJ_FACTOR_SUBP', 'ANN_BA_GROWTH', 'x',
                         'ANN_DIA_GROWTH', 'ANN_HT_GROWTH', 'ANN_NET_GROWTH', 'AREA AREA_SE', 'AREA_TOTAL',
                         'AREA_TOTAL_SE', 'AREA_USED', 'BAA', 'BAA_GROW', 'BAA_GROW_SE', 'BAA_PERC', 'BAA_PERC_SE',
                         'BAA_SE', 'BAA_TOTAL', 'BA_GROW', 'BA_GROW_SE', 'BA_SE', 'BA_TOTAL', 'BA_TOTAL_full', 'BIO',
                         'BIO_1000HR', 'BIO_1000HR_ACRE', 'BIO_100HR', 'BIO_100HR_ACRE', 'BIO_10HR',
                         'BIO_10HR_ACRE', 'BIO_1HR', 'BIO_1HR_ACRE', 'BIO_1HR_ACRE_SE', 'BIO_1HR_SE',
                         'BIO_ACRE', 'BIO_ACRE_SE', 'BIO_AG_ACRE', 'BIO_AG_TOTAL', 'BIO_BG_ACRE',
                         'BIO_BG_TOTAL', 'BIO_PILE', 'BIO_PILE_ACRE', 'BIO_PILE_ACRE_SE', 'BIO_PILE_SE',
                         'BIO_TOTAL', 'BIO_TOTAL_SE', 'CARB CARBON_AG', 'CARBON_BG CARB_1000HR',
                         'CARB_1000HR_ACRE', 'CARB_100HR', 'CARB_100HR_ACRE', 'CARB_10HR', 'CARB_10HR_ACRE',
                         'CARB_1HR', 'CARB_1HR_ACRE', 'CARB_1HR_ACRE_SE', 'CARB_1HR_SE', 'CARB_ACRE',
                         'CARB_ACRE_SE', 'CARB_AG_ACRE', 'CARB_AG_TOTAL', 'CARB_BG_ACRE','CARB_BG_TOTAL',
                         'CARB_PILE', 'CARB_PILE_ACRE', 'CARB_PILE_ACRE_SE', 'CARB_PILE_SE', 'CARB_TOTAL',
                         'CARB_TOTAL_SE', 'CCLCD', 'CN', 'CND_CN COMPONENT', 'CONDID', 'CONDPROP_UNADJ',
                         'COND_CHANGE_CD', 'COND_STATUS_CD', 'COND_STATUS_CD.CURR', 'COND_STATUS_CD.PREV',
                         'COUNTYCD', 'COVER_AREA', 'COVER_AREA_SE', 'COVER_PCT', 'COVER_PCT_SE',
                         'CWD_CARBON_ADJ', 'CWD_DRYBIO_ADJ', 'CWD_VOLCF_ADJ', 'DESIGNCD', 'DIA DIA_GROW',
                         'DIA_GROW_SE', 'DIA_TOTAL', 'DRYBIO_AG', 'DRYBIO_BG', 'END_INVYR', 'ESTN_METHOD',
                         'ESTN_UNIT_CN', 'EVALID', 'EVAL_CN', 'EVAL_TYP', 'EXPNS', 'EhCond', 'EhPlot', 'EhStrat', 'Eh_a',
                         'Eh_a_SE', 'Eh_b', 'Eh_g', 'Ehv', 'FUEL_TYPE', 'FWD_LG_CARBON_ADJ', 'FWD_LG_DRYBIO_ADJ',
                         'FWD_LG_VOLCF_ADJ', 'FWD_MD_CARBON_ADJ', 'FWD_MD_DRYBIO_ADJ', 'FWD_MD_VOLCF_ADJ',
                         'FWD_SM_CARBON_ADJ', 'FWD_SM_DRYBIO_ADJ', 'FWD_SM_VOLCF_ADJ', 'GENUS HT_GROW',
                         'HT_GROW_SE', 'HT_TOTAL', 'H_a', 'H_a_SE', 'H_b', 'H_g', 'INVASIVE_SAMPLING_STATUS_CD',
                         'LATE_AREA', 'LATE_AREA_SE', 'LATE_PERC', 'LATE_PERC_SE', 'MACRO_BREAKPOINT_DIA',
                         'MATURE_AREA', 'MATURE_AREA_SE', 'MATURE_PERC', 'MATURE_PERC_SE', 'MORT_PERC',
                         'MORT_PERC_SE', 'MORT_TOTAL', 'MORT_TOTAL_SE', 'MORT_TPA', 'MORT_TPA_SE',
                         'MOSAIC_AREA', 'MOSAIC_AREA_SE', 'MOSAIC_PERC', 'MOSAIC_PERC_SE', 'NETVOL_ACRE',
                         'NETVOL_AC_TOT', 'NETVOL_GROW', 'NETVOL_GROW_AC', 'NETVOL_GROW_AC_SE',
                         'NETVOL_GROW_SE', 'NETVOL_TOTAL', 'P1PNTCNT_EU', 'P1POINTCNT', 'P2POINTCNT',
                         'PERC_AREA', 'PERC_AREA_SE', 'PERC_SE', 'PILE_CARBON_ADJ', 'PILE_DRYBIO_ADJ',
                         'PILE_VOLCF_ADJ', 'PLOT PLT_CN', 'POLE_AREA', 'POLE_AREA_SE', 'POLE_PERC',
                         'POLE_PERC_SE', 'POP_EVAL', 'PROP_BASIS', 'RECR_PERC', 'RECR_PERC_SE', 'RECR_TOTAL',
                         'RECR_TOTAL_SE', 'RECR_TPA', 'RECR_TPA_SE', 'REMPER', 'REMV_PERC', 'REMV_PERC_SE',
                         'REMV_TOTAL', 'REMV_TOTAL_SE', 'REMV_TPA', 'REMV_TPA_SE', 'REPORT_YEAR_NM',
                         'SAWVOL_ACRE', 'SAWVOL_TOTAL', 'SPCD', 'SPECIES', 'STAGE', 'STATECD', 'STRATUM_CN', 'SUBP',
                         'SUBPTYP', 'SUBPTYP_GRM', 'SYMBOL', 'S_a', 'S_a_SE', 'S_b', 'S_g', 'TOTAL_AREA',
                         'TOTAL_AREA_SE', 'TOTAL_SE', 'TOTAL_TPA', 'TPA', 'TPAGROW_UNADJ', 'TPAMORT_UNADJ',
                         'TPAREMV_UNADJ', 'TPA_PERC', 'TPA_PERC_SE', 'TPA_SE', 'TPA_UNADJ', 'TREE', 'TREE_SE',
                         'TREE_TOTAL', 'TREE_TOTAL_SE', 'TREE_TOTAL_full', 'TRE_CN', 'VEG_SPCD', 'VOL', 'VOLCFNET',
                         'VOLCSNET', 'VOL_1000HR', 'VOL_1000HR_ACRE', 'VOL_100HR', 'VOL_100HR_ACRE', 'VOL_10HR',
                         'VOL_10HR_ACRE', 'VOL_1HR', 'VOL_1HR_ACRE', 'VOL_1HR_ACRE_SE', 'VOL_1HR_SE',
                         'VOL_ACRE', 'VOL_ACRE_SE', 'VOL_PILE', 'VOL_PILE_ACRE', 'VOL_PILE_ACRE_SE',
                         'VOL_PILE_SE', 'VOL_TOTAL', 'VOL_TOTAL_SE', 'YEAR', 'a', 'aAdj', 'aDI', 'aEst', 'aStrat', 'aVar',
                         'a_b', 'a_i', 'a_t', 'areaVar', 'av', 'bCV', 'bEst', 'bOut', 'bPlot', 'bStrat', 'bTEst', 'bTPlot',
                         'bTStrat', 'bTVar', 'bTv', 'bV', 'bVar', 'baVar', 'baaEst', 'baaPlot', 'baaStrat', 'baaVar',
                         'baagVar', 'baav', 'bagCV', 'bagEst', 'bagPlot', 'bagStrat', 'bagVar', 'bagaVar', 'bagv', 'bbgCV',
                         'bbgEst', 'bbgPlot', 'bbgStrat', 'bbgVar', 'bbgaVar', 'bbgv', 'bcCV', 'bcEst', 'bcPlot', 'bcStrat',
                         'bcV', 'bcVar', 'bgVar', 'blgCV', 'blgEst', 'blgPlot', 'blgStrat', 'blgV', 'blgVar', 'bmdCV',
                         'bmdEst', 'bmdPlot', 'bmdStrat', 'bmdV', 'bmdVar', 'bpCV', 'bpEst', 'bpPlot', 'bpStrat', 'bpV',
                         'bpVar', 'bsmCV', 'bsmEst', 'bsmPlot', 'bsmStrat', 'bsmV', 'bsmVar', 'btCV', 'btEst', 'btPlot',
                         'btStrat', 'btVar', 'btaVar', 'btv', 'bv', 'cCV', 'cEst', 'cPlot', 'cStrat', 'cV', 'cVar', 'cagCV',
                         'cagEst', 'cagPlot', 'cagStrat', 'cagVar', 'cagaVar', 'cagv', 'cbEst', 'cbgCV', 'cbgEst',
                         'cbgPlot', 'cbgStrat', 'cbgVar', 'cbgaVar', 'cbgv', 'ccCV', 'ccEst', 'ccPlot', 'ccStrat', 'ccV',
                         'ccVar', 'clgCV', 'clgEst', 'clgPlot', 'clgStrat', 'clgV', 'clgVar', 'cmdCV', 'cmdEst', 'cmdPlot',
                         'cmdStrat', 'cmdV', 'cmdVar', 'condArea', 'coverVar', 'cpCV', 'cpEst', 'cpPlot', 'cpStrat', 'cpV',
                         'cpVar', 'csmCV', 'csmEst', 'csmPlot', 'csmStrat', 'csmV', 'csmVar', 'ctCV', 'ctEst', 'ctPlot',
                         'ctStrat', 'ctVar', 'ctaVar', 'ctv', 'cv', 'cvB', 'cvBAA', 'cvBT', 'cvD', 'cvEst', 'cvEst_b', 'cvEst_bT',
                         'cvEst_baa', 'cvEst_bag', 'cvEst_bbg', 'cvEst_bt', 'cvEst_cag', 'cvEst_cbg', 'cvEst_ct',
                         'cvEst_d', 'cvEst_eh', 'cvEst_g', 'cvEst_ga', 'cvEst_h', 'cvEst_hT', 'cvEst_ht', 'cvEst_l',
                         'cvEst_m', 'cvEst_mT', 'cvEst_ma', 'cvEst_mo', 'cvEst_nv', 'cvEst_p', 'cvEst_r', 'cvEst_rT',
                         'cvEst_s', 'cvEst_sv', 'cvEst_t', 'cvEst_tT', 'cvG', 'cvGA', 'cvH', 'cvHT', 'cvL', 'cvM', 'cvMT', 'cvMa',
                         'cvMo', 'cvP', 'cvR', 'cvRT', 'cvS', 'cvStrat', 'cvStrat_Eh', 'cvStrat_b', 'cvStrat_baa',
                         'cvStrat_bag', 'cvStrat_bbg', 'cvStrat_bt', 'cvStrat_cag', 'cvStrat_cbg', 'cvStrat_ct',
                         'cvStrat_d', 'cvStrat_g', 'cvStrat_ga', 'cvStrat_h', 'cvStrat_hT', 'cvStrat_ht',
                         'cvStrat_l', 'cvStrat_m', 'cvStrat_mT', 'cvStrat_ma', 'cvStrat_mo', 'cvStrat_nv',
                         'cvStrat_p', 'cvStrat_r', 'cvStrat_rT', 'cvStrat_s', 'cvStrat_sv', 'cvStrat_t', 'cvT',
                         'cvTT', 'cveH', 'dEst', 'dPlot', 'dStrat', 'dVar', 'db', 'dgVar', 'dv', 'eh', 'ehVar', 'expInv', 'fVar', 'fa',
                         'faFull', 'faFullmo', 'fullDI', 'fullEst', 'fullStrat', 'fullVar', 'fullv', 'gEst', 'gPlot',
                         'gStrat', 'gVar', 'gaEst', 'gaPlot', 'gaStrat', 'gaVar', 'gagVar', 'gav', 'ggVar', 'gv', 'h', 'hCond',
                         'hEst', 'hPlot', 'hStrat', 'hVar', 'haVar', 'htEst', 'htPlot', 'htStrat', 'htVar', 'htgVar', 'htv', 'hv',
                         'iEst', 'iPlot', 'iPlots', 'iStrat', 'iVar', 'iv', 'l', 'lEst', 'lStrat', 'lVar', 'lpVar', 'lv', 'mEst',
                         'mPlot', 'mStrat', 'mVar', 'ma', 'maEst', 'maStrat', 'maVar', 'mapVar', 'mav', 'mo', 'moEst', 'moStrat',
                         'moVar', 'mopVar', 'mov', 'mtVar', 'mv', 'nPlots', 'nPlots_AREA', 'nPlots_INV', 'nPlots_TREE',
                         'nPlots_VOL', 'nStands', 'nh', 'nvCV', 'nvEst', 'nvPlot', 'nvStrat', 'nvVar', 'nvaVar', 'nvv', 'p', 'p1',
                         'p1EU', 'p1EU_a', 'p1_b', 'p1_i', 'p1_t', 'p2', 'p2_b', 'p2_i', 'p2_t', 'pDI', 'pEst', 'pStrat', 'pVar',
                         'plotIn', 'plotIn_AREA', 'plotIn_TREE', 'plotIn_a', 'plotIn_t', 'plotSF', 'plotsInv',
                         'polyID', 'ppVar', 'propVar', 'pv', 'rEst', 'rPlot', 'rStrat', 'rVar', 'raVar', 'rtVar', 'rv', 's', 'sCond',
                         'sPlot', 'sStrat', 'sVar', 'stage', 'sv', 'svCV', 'svEst', 'svPlot', 'svStrat', 'svVar', 'svaVar', 'svv',
                         'tAdj', 'tDI', 'tEst', 'tPlot', 'tStrat', 'tTEst', 'tTPlot', 'tTStrat', 'tTVar', 'tTv', 'tVar', 'totals',
                         'tpVar', 'tpaVar', 'treeVar', 'tv', 'vCV', 'vEst', 'vPlot', 'vStrat', 'vV', 'vVar', 'vcCV', 'vcEst',
                         'vcPlot', 'vcStrat', 'vcV', 'vcVar', 'vlgCV', 'vlgEst', 'vlgPlot', 'vlgStrat', 'vlgV', 'vlgVar',
                         'vmdCV', 'vmdEst', 'vmdPlot', 'vmdStrat', 'vmdV', 'vmdVar', 'vpCV', 'vpEst', 'vpPlot', 'vpStrat',
                         'vpV', 'vpVar', 'vsmCV', 'vsmEst', 'vsmPlot', 'vsmStrat', 'vsmV', 'vsmVar', 'w',
                         'AREA', 'AREA_SE', 'CARB', 'CARBON_AG', 'CARBON_BG', 'CARB_1000HR', 'CND_CN', 'COMPONENT',
                         'DIA', 'DIA_GROW', 'GENUS', 'HT_GROW', 'PLOT', 'PLT_CN', 'maxYear', 'aD', 'LOCATION_NM',
                         'grpVar', 'm', 'xVar', 'yVar', 'LAT', 'LON', 'PREVCOND', 'PREV_PLT_CN', 'STATE',
                         'BIO_DUFF', 'BIO_DUFF_ACRE', 'BIO_DUFF_ACRE_SE', 'BIO_DUFF_SE', 'BIO_LITTER',
                         'BIO_LITTER_ACRE', 'CARB_DUFF', 'CARB_DUFF_ACRE', 'CARB_DUFF_ACRE_SE',
                         'CARB_DUFF_SE', 'CARB_LITTER', 'CARB_LITTER_ACRE', 'DUFF_BIOMASS', 'DUFF_CARBON',
                         'LITTER_BIOMASS', 'LITTER_CARBON', 'SUBP_COMPONENT_AL_FOREST',
                         'SUBP_COMPONENT_AL_TIMBER', 'SUBP_COMPONENT_GS_FOREST',
                         'SUBP_COMPONENT_GS_TIMBER', 'SUBP_SUBPTYP_GRM_AL_FOREST',
                         'SUBP_SUBPTYP_GRM_AL_TIMBER', 'SUBP_SUBPTYP_GRM_GS_FOREST',
                         'SUBP_SUBPTYP_GRM_GS_TIMBER', 'SUBP_TPAGROW_UNADJ_AL_FOREST',
                         'SUBP_TPAGROW_UNADJ_AL_TIMBER', 'SUBP_TPAGROW_UNADJ_GS_FOREST',
                         'SUBP_TPAGROW_UNADJ_GS_TIMBER', 'SUBP_TPAMORT_UNADJ_AL_FOREST',
                         'SUBP_TPAMORT_UNADJ_AL_TIMBER', 'SUBP_TPAMORT_UNADJ_GS_FOREST',
                         'SUBP_TPAMORT_UNADJ_GS_TIMBER', 'SUBP_TPAREMV_UNADJ_AL_FOREST',
                         'SUBP_TPAREMV_UNADJ_AL_TIMBER', 'SUBP_TPAREMV_UNADJ_GS_FOREST',
                         'SUBP_TPAREMV_UNADJ_GS_TIMBER', 'VOL_DUFF', 'VOL_DUFF_ACRE', 'VOL_DUFF_ACRE_SE',
                         'VOL_DUFF_SE', 'bdCV', 'bdEst', 'bdPlot', 'bdStrat', 'bdV', 'bdVar', 'blCV', 'blEst', 'blPlot',
                         'blStrat', 'blV', 'blVar', 'cdCV', 'cdEst', 'cdPlot', 'cdStrat', 'cdV', 'cdVar', 'clCV', 'clEst',
                         'clPlot', 'clStrat', 'clV', 'clVar', 'dbConnect', 'dbListTables', 'nPlots_MORT',
                         'nPlots_RECR', 'nPlots_REMV', 'p1_eu', 'plotIn_g', 'plotIn_h', 'plotIn_m', 'plotIn_r', 'progress', 'totalPlots',
                         'COND_STATUS_CD.chng', 'COND_STATUS_CD.prev', 'GROWTH_ACCT', 'geometry', 'lazy_dt',
                         'BIO_AC_TOT', 'BIO_GROW', 'BIO_GROW_AC', 'BIO_GROW_AC_SE', 'BIO_GROW_SE', 'DIA.mid',
                         'DIA.prev', 'DRYBIO_AG.mid', 'DRYBIO_AG.prev', 'INVYR', 'VOLCFNET.mid',
                         'VOLCFNET.prev', 'bioAPlot', 'bioEst', 'bioPlot', 'bioStrat', 'bioVar', 'bioaEst',
                         'bioaStrat', 'bioaVar', 'bioagVar', 'bioav', 'biogVar', 'biov', 'cvBIO', 'cvBIOA', 'cvEst_bio',
                         'cvEst_bioa', 'cvStrat_bio', 'cvStrat_bioa',
                         'BIO_AG_ACRE_SE', 'BIO_BG_ACRE_SE', 'CARB_AG_ACRE_SE', 'CARB_BG_ACRE_SE',
                         'NETVOL_ACRE_SE', 'SAWVOL_ACRE_SE', 'SUBPTYP_PROP_CHNG',
                         'BA', 'BA1', 'BA2', 'DIA.beg', 'DIA1', 'DIA2', 'DRYBIO_AG.beg', 'DRYBIO_AG1', 'DRYBIO_AG2',
                         'ONEORTWO', 'VOLCFNET.beg', 'VOLCFNET1', 'VOLCFNET2', 'VOLCSNET.beg', 'VOLCSNET.mid',
                         'VOLCSNET.prev', 'ga', 'se', 'ba', 'baa', 'd', 'vol', 'volA', 'place'))
